version: "2.4"

services:
  mongo:
    image: mongo
    container_name: mongodb
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes: 
      - mongo_data:/data/db
    networks:
      - mongo_network
    ports: 
      - 27017:27017

  mongo-express:
    image: mongo-express
    environment: 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
    depends_on: 
      - mongo
    networks: 
      - mongo_network      
    ports: 
      - 20048:8081

  arkon-app:
    image: arkon-app:dev
    environment: 
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - DB_NAME=${DB_NAME}
      - DB_TYPE=${DB_TYPE}
      - URL_API_MB=${URL_API_MB}
      - URL_API_POSTCODE=${URL_API_POSTCODE}
      - URL_GEO_REVERSE=${URL_GEO_REVERSE}
      - URL_API_POSTCODE_KEY=${URL_API_POSTCODE_KEY}
    depends_on: 
      - mongo
    networks: 
      - mongo_network
    ports: 
      - 8000:8000
    volumes: 
      - ./src:/src

networks: 
  mongo_network:
    driver: bridge

volumes: 
  mongo_data: